config/routes.rb
Rails.application.routes.draw do
  get 'setting/mailDetails'

  post 'setting/create'

  get 'setting/edit'

  patch 'setting/update'

  get 'test/show'

  get 'admin/index'

  get 'admin/new'

  post 'admin/create'

  get 'admin/edit'

  patch 'admin/update'

  devise_for :users
  get 'home/index'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :hostaddress,:port,:user_name,:password,:enable_ssl,:protocol, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :congrats_email

  mount_uploader :avatar, AvatarUploader

  validates :firstname,:lastname,:contact,:position,:email,:address,:dob,:accessLevel, :password, :password_confirmation,presence: true


  def congrats_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.where('id != ?',current_user.id)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:firstname,:lastname,:contact,:position,:email,:address,:dob,:avatar, :password,:accessLevel, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
          |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
          |u| u.permit(registration_params)
      }
    end
  end



# If your model is called User
  def after_sign_in_path_for(resource)
    home_index_path
  end

  def after_sign_up_path_for(resource)

    home_index_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
  def mailDetails
    @setting = Setting.new
  end

   def create
     @setting = Setting.new(setting_params)
     if @setting.save
       redirect_to home_index_path
     else
       render 'mailDetails'
     end
   end

  def edit
    @setting = Setting.find(params[:format])
    end

  def update
    @setting = Setting.find_by(params[:format])
    if @setting.update_attributes
      redirec_to home_index_path
    else
      render 'edit'
    end

  end

  protected

  def setting_params
    params.require(:setting).permit(:hostaddress,:port,:user_name,:password,:enable_ssl,:protocol)
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def show

   # mail = Mail.defaults do
    #  retriever_method :pop3, :address    => "mail.ignisitsolutions.com",
   #                    :port       => 110,
    #                   :user_name  => 'ankit@ignisitsolutions.com',
     #                  :password   => 'ankit12345',
     #                  :enable_ssl => false
   # end

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mymailer_helper.rb
module MymailerHelper

  def send_email(from = 'support@mail.com', to , subject , message)

    mail = Mail.new do
      from     from
      to       to
      subject  subject
      body     message
    end

    mail.deliver!
  end

end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/admin/edit.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/admin/index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>
        User's
        <small>
          list
        </small>
      </h3>
    </div>

    <div class="title_right">

    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Active users</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a href="#"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="example" class="table table-striped responsive-utilities jambo_table">
            <thead>
            <tr class="headings">
              <th>Id</th>
              <th>User Name</th>
              <th>Contact</th>
              <th>Email Address</th>
              <th>Position</th>
              <th>Created At</th>
              <th class=" no-link last"><span class="nobr">Action</span>
              </th>
            </tr>
            </thead>

            <tbody>
            <% @user.each do |data| %>
            <tr class="even pointer">
              <td class=" "><%= data.id %></td>
              <td class=" "><%= data.firstname %> <%= data.lastname %></td>
              <td class=" "><%= data.contact %></td>
              <td class=" "><%= data.email %></td>
              <td class=" "><%= data.position %></td>
              <td class=" "><%= data.created_at %></td>
              <td class=" last"><a href="#">View</a>
              </td>
            </tr>
             <% end %>
            </tbody>

          </table>
        </div>
      </div>
    </div>

    <br />
    <br />
    <br />

  </div>
</div>
</div>

app/views/admin/new.html.erb
<h1>Admin#new</h1>
<p>Find me in app/views/admin/new.html.erb</p>

app/views/common/_sidenav.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">

    <div class="navbar nav_title" style="border: 0;">
      <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Management</span></a>
    </div>
    <div class="clearfix"></div>

    <!-- menu prile quick info -->
    <div class="profile">
      <div class="profile_pic">
        <img src="<%= current_user.avatar.url %>" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2><%= current_user.firstname %></h2>
      </div>
    </div>
    <!-- /menu prile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

      <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <% if current_user.accessLevel == "Admin" %>
              <li><a href="<%= admin_index_path %>">User's List</a>
              </li>
              <% end %>
              <li><a href="index2.html">Dashboard2</a>
              </li>
              <li><a href="index3.html">Dashboard3</a>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-envelope-o"></i> Mail <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><a href="form.html">Compose</a>
              </li>
              <li><a href="form_advanced.html">Inbox</a>
              </li>
              <li><a href="form_validation.html">Outbox</a>
              </li>
              <li><a href="form_wizards.html">Trash</a>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><a href="general_elements.html">General Elements</a>
              </li>
              <li><a href="media_gallery.html">Media Gallery</a>
              </li>
              <li><a href="typography.html">Typography</a>
              </li>
              <li><a href="icons.html">Icons</a>
              </li>
              <li><a href="glyphicons.html">Glyphicons</a>
              </li>
              <li><a href="widgets.html">Widgets</a>
              </li>
              <li><a href="invoice.html">Invoice</a>
              </li>
              <li><a href="inbox.html">Inbox</a>
              </li>
              <li><a href="calender.html">Calender</a>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><a href="tables.html">Tables</a>
              </li>
              <li><a href="tables_dynamic.html">Table Dynamic</a>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><a href="chartjs.html">Chart JS</a>
              </li>
              <li><a href="chartjs2.html">Chart JS2</a>
              </li>
              <li><a href="morisjs.html">Moris JS</a>
              </li>
              <li><a href="echarts.html">ECharts </a>
              </li>
              <li><a href="other_charts.html">Other Charts </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="menu_section">
        <h3>Live On</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><a href="e_commerce.html">E-commerce</a>
              </li>
              <li><a href="projects.html">Projects</a>
              </li>
              <li><a href="project_detail.html">Project Detail</a>
              </li>
              <li><a href="contacts.html">Contacts</a>
              </li>
              <li><a href="profile.html">Profile</a>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><a href="page_404.html">404 Error</a>
              </li>
              <li><a href="page_500.html">500 Error</a>
              </li>
              <li><a href="plain_page.html">Plain Page</a>
              </li>
              <li><a href="login.html">Login Page</a>
              </li>
              <li><a href="pricing_tables.html">Pricing Tables</a>
              </li>

            </ul>
          </li>
          <li><a><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a>
          </li>
        </ul>
      </div>

    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Logout">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      </a>
    </div>
    <!-- /menu footer buttons -->
  </div>
</div>

app/views/common/_topnav.html.erb
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="<%= current_user.avatar.url %>"alt=""><%= current_user.firstname %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
            <li><a href="<%= edit_user_registration_path(current_user.id) %>">  Profile</a>
            </li>
            <li>
              <a href="<%= setting_mailDetails_path %>">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li>
              <a href="javascript:;">Help</a>
            </li>
            <li>
              <a href="<%= destroy_user_session_path %>" data-method="delete"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
            </li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list animated fadeInDown" role="menu">
            <li>
              <a>
                                            <span class="image">
                                        <img src="<%= image_url('img.jpg') %>" alt="Profile Image" />
                                    </span>
                                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                                            <span class="image">
                                        <img src="<%= image_url('img.jpg') %>" alt="Profile Image" />
                                    </span>
                                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                                            <span class="image">
                                        <img src="<%= image_url('img.jpg') %>"alt="Profile Image" />
                                    </span>
                                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                                            <span class="image">
                                        <img src="<%= image_url('img.jpg') %>" alt="Profile Image" />
                                    </span>
                                            <span>
                                        <span>John Smith</span>
                                            <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <div class="text-center">

                <strong><a href="inbox.html">See All Alerts</a></strong>
                <i class="fa fa-angle-right"></i>

              </div>
            </li>
          </ul>
        </li>

      </ul>
    </nav>
  </div>

</div>

app/views/home/index.html.erb
<div class="right_col" role="main">

  <h1>test</h1>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Office Management!</title>

  <title>Office</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="nav-md">
<div class="container body">


  <div class="main_container">
    <% if current_user %>
    <%= render "common/sidenav" %>
    <!-- top navigation -->
    <%= render "common/topnav" %>
   <% end %>
    <%= yield %>
  </div>

</div>
</body>
</html>

app/views/setting/_form.html.erb
<div class="x_content">
  <%= form_for(@setting,url: setting_create_path(@setting),  :html => {:class => "form-horizontal form-label-left",:novalidate=>"novalidate"}) do |f| %>

      <span class="section"> IMAP, POP3, and SMTP Details</span>

      <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="website">Host Address	 <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.text_field :hostaddress, autofocus: true,:class=>'form-control' , :required =>'required',:placeholder=>"www.website.com" %>
        </div>

        <% if @setting.errors[:hostaddress].present? %>
            <ul class="parsley-errors-list filled" id="parsley-id-2042"><li class="parsley-required">This value is required.</li></ul>
        <% end %>
      </div>
      <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">Port <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.text_field :port,:class=>'form-control' , :required =>'required',:placeholder=>"Port" %>
        </div>
        <% if @setting.errors[:port].present? %>
            <ul class="parsley-errors-list filled" id="parsley-id-2042"><li class="parsley-required">This value is required.</li></ul>
        <% end %>
      </div>
      <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">User Name / Email <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.text_field :user_name,:class=>'form-control' , :required =>'required',:placeholder=>"User Name / Email" %>
        </div>
        <% if @setting.errors[:user_name].present? %>
            <ul class="parsley-errors-list filled" id="parsley-id-2042"><li class="parsley-required">This value is required.</li></ul>
        <% end %>
      </div>
      <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Password <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.text_field :password,:class=>'form-control' , :required =>'required',:placeholder=>"Password" %>
        </div>
        <% if @setting.errors[:password].present? %>
            <ul class="parsley-errors-list filled" id="parsley-id-2042"><li class="parsley-required">This value is required.</li></ul>
        <% end %>
      </div>
      <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Enable SSL Status <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.text_field :enable_ssl,:class=>'form-control' , :required =>'required',:placeholder=>"Enable SSL Status" %>
        </div>
        <% if @setting.errors[:enable_ssl].present? %>
            <ul class="parsley-errors-list filled" id="parsley-id-2042"><li class="parsley-required">This value is required.</li></ul>
        <% end %>
      </div>

      <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="website">Protocol <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.select(:protocol,  [["POP3", "POP3"], ["IMAP", "IMAP"],["SMTP","SMTP"]], {include_blank: "Select something"}, { :class=>'form-control' }) %>
        </div>
        <% if @setting.errors[:protocol].present? %>
            <ul class="parsley-errors-list filled" id="parsley-id-2042"><li class="parsley-required">This value is required.</li></ul>
        <% end %>
      </div>
      <div class="ln_solid"></div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <button type="submit" class="btn btn-primary">Cancel</button>
          <button id="send" type="submit" class="btn btn-success">Submit</button>
        </div>
      </div>
  <% end %>

</div>

app/views/setting/edit.html.erb
<!-- page content -->
<div class="right_col" role="main">

  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>
          Settings
        </h3>
      </div>

    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Mail Server <small>detail</small></h2>

            <div class="clearfix"></div>
          </div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>



</div>
<!-- /page content -->

app/views/setting/mailDetails.html.erb
<!-- page content -->
<div class="right_col" role="main">

  <div class="">
    <div class="page-title">
      <div class="title_left">
       <a class="btn btn-sm btn-success" href="<%= setting_edit_path(current_user.id) %>">Edit My Details</a>
      </div>

    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Mail Server <small>detail</small></h2>

            <div class="clearfix"></div>
          </div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>



</div>
<!-- /page content -->